sonar.projectKey=glare247-org_theepicbook
sonar.organization=glare247-org
sonar.projectName=theepicbook
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,terraform/**,gitops/**,public/assets/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
